default: true
MD013:
  line_length: 120
MD024: false
MD033:
  allowed_elements:
    - code
    - pre
    - kbd
    - details
    - summary
MD041: false
MD046:
  style: fenced
ol-prefix:
  style: ordered
no-bare-urls: true